app = "lawdata"
primary_region = "sin"

[mounts]
source = "db_lawdata"
destination = "/data"

[http_service]
  internal_port = 8080
  force_https = true
  auto_start_machines = true

  [[http_service.tcp_checks]]
  interval = "10000"
  timeout = "5000"
