[tool.poetry]
name = "corpus-datasette"
version = "0.0.1"
description = "Datasette instance of corpus-x database."
authors = ["Marcelino G. Veloso III <mars@veloso.one>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
python-dotenv = "^0.21"
datasette = "^0.63.3"
datasette-pretty-json = "^0.2.2"
datasette-auth-tokens = "^0.3"
datasette-auth-github = "^0.13.1"
datasette-query-files = "^0.1.1"

[tool.poetry.group.dev.dependencies]
pre-commit = "^2.21"

[tool.black]
target-version = ['py311']
line-length = 79
include = '.pyi?$'
exclude = '''
/(
    .git
    | .hg
    | .mypy_cache
    | .tox
    | .venv
    | _build
    | buck-out
    | build
    | dist
)/
'''

[tool.isort]
profile = "black"
multi_line_output = 3
line_length = 79
include_trailing_comma = 'True'

[build-system]
requires = ["poetry-core>=1.3.2"]
build-backend = "poetry.core.masonry.api"
